#!/bin/sh

SOURCE_DIR=/opt/waze/data
WAZE_TARGET_DIR=/home/user/MyDocs/.waze

echo Deploying Waze data to ${WAZE_TARGET_DIR}
mkdir -p ${WAZE_TARGET_DIR}
cp -r ${SOURCE_DIR}/* ${WAZE_TARGET_DIR} 2> /dev/null
